### ISSUE TITLE
mpirun mdrun fails with`There are not enough slots available`

### ISSUE THREAD

**Issue by zh2417** [luancarvalhomartins/PyAutoFEP#119]
Hello author, I'm sorry to take up your time.
[](url)mpirun -np $(ls | egrep "lambda[0-9]+$" | wc -l) gmx_mpi mdrun -v --deffnm lambda -cpi lambda.cpt -multidir $(ls -v | egrep "lambda[0-9]+$") >& feprun_$(date "+%H%M%S_%d%m%Y").log || { echo "mdrun failed at line ${LINENO} "; exit -1; }
I found an error with this command in the sh file，Log display
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/72326396/3b02df6d-1b05-4548-9b32-32b5edefa0fc)
![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/72326396/485635f9-0b72-4b4c-ba1c-278aeb40a327)
I found that my machine is a single machine with only 10 gpu cores, so I try to modify the code as follows, and it can run
mpirun -np 10 gmx_mpi mdrun -v --deffnm lambda -cpi lambda.cpt -multidir lambda0 lambda1 lambda2 lambda3 lambda4 lambda5 lambda6 lambda7 lambda8 lambda9  >& feprun_$(date "+%H%M%S_%d%m%Y").log || { echo "mdrun failed at line ${LINENO} "; exit -1; } 

Your default number of lambdas is 12, which will cause a conflict.Please tell me which file should I modify the number of lambdas in order to be compatible with my machine? Or do you have any better ways to solve this problem?

**Comment by luancarvalhomartins** [comment]
Thank you very much for your message and for your interest in PyAutoFEP.

What you need is not less slots to be requested, which would left some lambda windows to not be run. In order to run less lambda windows, you would actually need to set that when running `prepare_dual_topology.py`.

Instead, you need to allow `mpirun` oversubscribe ranks to your cores. For openmpi, see `rmaps_base_oversubscribe`. Or add `--oversubscribe` to the `mpirun` call in the run script.

On a second thought, allowing oversubscribe could be the default, at the risk that problematic job configurations (ie, asking for too few cores) won't rise any error.
