### ISSUE TITLE
Support for morphing between two ligands

### ISSUE THREAD

**Issue by xiki-tempula** [luancarvalhomartins/PyAutoFEP#14]
I'm testing the PyAutoFEP and would like to start with the simplest case of morphing between two ligands.
I tried to use the star mapping scheme.

`python ~/GitHub/PyAutoFEP/generate_perturbation_map.py --map_type=star --map_bias=RVXOH --input lig_data/*.mol2`

However, I'm getting:

```
[ERROR] A total of molecules 2 were read. I need at least 3 to construct a meaningful perturbation graph
=================== STACK INFO ===================
  File "/Users/zhiyiwu/GitHub/PyAutoFEP/generate_perturbation_map.py", line 475, in <module>
    current_verbosity=arguments.verbose)
  File "/Users/zhiyiwu/GitHub/PyAutoFEP/os_util.py", line 292, in local_print
    formatted_string += '\n{:=^50}\n{}{:=^50}'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================
```

I wonder if there is support for two molecules morphing as well?

**Comment by xiki-tempula** [comment]
@luancarvalhomartins Thank you for all the work, I wonder if I could have some advice on how to write the config file, please? Thank you.

**Comment by luancarvalhomartins** [comment]
Sorry for the latiness. Activities in closed issues aren't as visible as in open ones. It's quite late here, but I am replying tomorrow.

**Comment by xiki-tempula** [comment]
@luancarvalhomartins No worries. I thought that I'm too lazy and don't want to help me. I think it might be better to allow users to reopen a closed issue.

**Comment by luancarvalhomartins** [comment]
Ok, I was a bit busy these days. Here's what happened: I prepared the config file to use your inputs, but then I found out that an old bug that I tought I fixed long ago is still there. It affects the align code for pre-solvated systems. I am working on it right now and I hope I commit a fix soon.

In the meantime, in case you are in a rush, I suggest you to strip the water and ion molecules from your systems and use the PyAutoFEP system builder. In case you would like to try that and you need any help, don't hesitate to write me (by email, please, it's much better than use this closed issue - luancarvalhomartins@gmail.com).

Find below my original answer - it won't work with the current trunk, tought. I am posting it here for future reference.

Preliminaries: install `biopython`, which is used to align proteins in the PDB loading function, and `mdanalysis`, which is used to find waters too close to the ligand in the input PDB.

I noted some points in your setup that PyAutoFEP won't handle:
 - The ligand topology includes the protein topology. This is not supported (it could work if all parameters were inline, but it's absolutely not how PyAutoFEP expects the ligand topologies to be). So I moved the ligand atomtypes to ligand.atp files and a added a `#include "ligand.atp"` to topol.top in RVXOH and RVX208.
 - .gro files are not supported as structure inputs, so I converted the RVXOH/em.gro to RVXOH/RVXOH.pdb and the RVX208/em.gro to RVX208/RVX208.pdb, using openbabel. Also, the ligand name in RVXOH.pdb is UNL and in RVX208.pdb it's LIG, which is not currently supported - but I guess it would be useful, maybe I will add it in the future. I renamed RVXOH.pdb ligand to LIG.
 - The molecule names in lig_data/RVX208.mol2 and lig_data/RVXOH.mol2 are the same. PyAutoFEP will use the mol2 molecule name by default, so I renamed the molecules in lig_data/RVX208.mol2 and lig_data/RVXOH.mol2. (Note: I actually removed that limitation in trunk).

You didn't specify how the starting positions should be read. Lets use your MD structures, after converting them to PDB (see above).

So, preparing the config file point by point
_This is a simple morphing from one molecule RVXOH to another molecule RVX208._
Set `perturbation_map=RVXOH: RVX208`

_The full prepared coordinate (solvated with ions) for RVXOH and RVX208 are in RVX208/em.gro and RVXOH/em.gro (I have ensured that they have the same number of water and ions)._
Convert the full system to be used as reference (ie, the A state, so RVXOH) to PDB an use `structure=RVXOH/em.pdb` or whatever the file name you choose. Also, set `pre_solvated=True`.

_The mol2 file of two ligands are in lig_data/RVX208.mol2 and lig_data/RVXOH.mol2_
_The atomtypes of the two ligands are in RVX208/topol.top and RVXOH/topol.top_
_The ligand topology is in RVX208/ligand.itp and RVXOH/ligand.itp_
Ok, so you need to pass the exact file locations to `prepare_dual_topology.py`. Note that I moved the atomtypes to RVXOH/ligand.atp and RVX208/ligand.atp. Let's pass data to `input_ligands` using a dict: `input_ligands=RVX208: lig_data/RVX208.mol2, RVX208/ligand.atp, RVX208/ligand.itp; RVXOH: lig_data/RVXOH.mol2, RVXOH/ligand.atp, RVXOH/ligand.itp`. Note the use of commas and a semicolon to format the dict (which is covered in the manual)

_The protein topology are in RVX208/topol.top and RVXOH/topol.top_
Only one of the system topologies, that of the reference system (state A), will be used. Use `topology=RVXOH/topol.top`

_The force files file is the amber14sb.ff._
Pass `amber14sb.ff` dir to `extradirs`. Remember that a water system will be build, so `prepare_dual_topology.py` must be able to prepare a water topology using your topology. Also, make sure to select the correct water model in case you are not using the forcefield default (I guess you are, based on your .gro files).

You will need to use the PDB pose loader. Note that I renamed the files, so that prepare_dual_topology.py will know which pose is which. Set `pose_loader=pdb` and use `poses_input=RVX208: RVX208/RVX208.pdb; RVXOH: RVXOH/RVXOH.pdb` to pass the files.

Also, please find attached the config file as txt
[config.txt](https://github.com/luancarvalhomartins/PyAutoFEP/files/7523112/config.txt)

**Comment by luancarvalhomartins** [comment]
Ok, I think I solved it. Commit https://github.com/luancarvalhomartins/PyAutoFEP/commit/05aea6f749ddca8ed8df26c5ad9dde34aba4b1c5 likely solves the problem. Also, stripping water molecules from input poses drastically improves performance. A option to ignore them automatically would be great.
