### ISSUE TITLE
suggestion about install

### ISSUE THREAD

**Issue by zfb601** [luancarvalhomartins/PyAutoFEP#50]
The software "parallel" should be mentioned in the installation part.

Further, I use a single node workstation. I need to modify some commands. I'm not sure if it's because of my software environment.
For runall_***_protein.sh, line 221, "gmx mdrun -v" need to be changed to "gmx_mpi mdrun -v"
For runall_***_water.sh, line 197,  "gmx mdrun -v" need to be changed to "gmx_mpi mdrun -v"

**Comment by luancarvalhomartins** [comment]
Thanks fo the suggestion. Indeed, GNU `parallel` is currently a requirement for the rerun step. Maybe a future version may add a fallback to some alternative, eg `xargs`. (Is `xargs` even more available than `parallel`? I'm not sure).

Instead of modifying the `runall_X-X_{water,protein}.sh`, you should set the `gmx` used in the run node by passing the `gmx_bin_run` option to `prepare_dual_topology.py`. Take a look at `output_runbefore` and `output_runafter` also, which should avoid the need of editing the run scripts. If you find that the run script still must be modified afterwards, please, let me know so that I we can try finding another way around.

**Comment by zfb601** [comment]
Thanks for you reply!

my gmx install path is /usr/local/gromacs/bin
I've tried the following modifications in step2.ini:
gmx_bin_run=/usr/local/gromacs/bin     crash immediately
gmx_bin_run=/usr/local/gromacs/bin/GMXRC     crash immediately
gmx_bin_run=/usr/local/gromacs/bin/GMXRC.bash      crash immediately
gmx_bin_run=/usr/local/gromacs/bin/gmx     same as make no modification.

It ONLY works when I change the "gmx mdrun -v" to "gmx_mpi mdrun -v"
Here's Error in the log (feprun_X_X.log), when I made no change.
Feature not implemented:
Multi-simulations are only supported when GROMACS has been configured with a
proper external MPI library.

My environment:
single node workstation
ubuntu 20.04LTS
anaconda 2022
python 3.7.11
rdkit 2020.09.1.0
openbabel 2.4.1
networkx 2.6.3
pymbar 3.0.5
alchemlyb 0.6.0

**Comment by luancarvalhomartins** [comment]
`gmx_bin_run` must point to the GROMACS binary, not to the install dir:
```
  --gmx_bin_run GMX_BIN_RUN
                        Use this Gromacs binary to run the MD. This should be
                        the Gromacs bin in the run node, not in the current
                        machine. (Default: gmx)
```
Your GROMACS install path is `/usr/local/gromacs/bin`, therefore the binary is (or should be) `/usr/local/gromacs/bin/gmx_mpi`, so:

```
gmx_bin_run=/usr/local/gromacs/bin/gmx_mpi
```
should work. `/usr/local/gromacs/bin/` seems to be in your path, so
```
gmx_bin_run=gmx_mpi
```
should also work.

Note that in case `/usr/local/gromacs/bin` is not in your path, you maybe inadvertently running using another install.

---
Documentation updated to include `GNU parallel`, consider adding a fallback to `xargs` in a future update
