### ISSUE TITLE
 Could not find topology data for ligand xxx.pdb

### ISSUE THREAD

**Issue by Glinttsd** [luancarvalhomartins/PyAutoFEP#60]
Hi, I encoutered `Could not find topology data for ligand xxx.pdb` error at the `prepare_dual_topology.py --config_file=step2.ini` stage. Detailed massages are in `stdout.log` within the attachment `FEP.zip`. I think I have well prepared all the topology files, which are in `lig_data` dir

`
[FEP.zip](https://github.com/luancarvalhomartins/PyAutoFEP/files/9394041/FEP.zip)
`

**Comment by luancarvalhomartins** [comment]
It seems that your progress file contains partial ligand data that was generated using other ligand names or file locations. The input reader code, then, fails because it didn't understand that `lig_data/XXX.pdb` is the same molecule as `XXX.pdb`. Code tries to be smart regarding mol names, but it is not smart enough.

In this particular case, I suggest you to remove your `progress.pkl` file, generate a new one using `generate_perturbation_map.py` (or skip it altogether and pass `perturbation_map` to `prepare_dual_topology.py`), then run `prepare_dual_topology.py` again.

Also, I noted that you set `output_resources` in your config file, but that only makes sense when using `output_scripttype = slurm` or `output_scripttype = pbs` (ie, using a job scheduler).

**Comment by Glinttsd** [comment]
Hi, I solved the problem by converting `.pdb` files to '.mol' and renaming them carfully. 

Regarding to the `slurm` and `pbd`, I am not familiar with the scheduler thing and I think they may not compatible with my enviroment, so I decided to not use them.

I also noticed that `runall.sh` contains several serial scripts, which are independent from each other. I wonder whether I could run each of them on a CPU node and merge them altogether when they are all finished (and then run pack.sh etc.). Is it a possible way to accelerate the whole process without influencing the correctness?

**Comment by luancarvalhomartins** [comment]
Glad to know that you were able to solve the problem.

Running on a CPU-only node (ie, no GPU available) is possible, but extremely slow. Each leg of each perturbation pair is independent and running on several nodes is likely the most common way to proceed. Usually, this is accomplished using a job scheduler. `slurm` is quite simple to install. In case you have several nodes, I would suggest you to take a look. If you want to run in several nodes using `bash` you will have to find a way to manage the runs. The simplest way is probably editing `runall.sh` and run some of the legs/ligands on each node.

PS: I am closing the issue, but feel free to reply here, open another issue or reach me by email (luancarvalhomartins@gmail.com) should you need any help.
