### ISSUE TITLE
Ddg_vs_time does not converge in the FEP calculations of FXR_12-FXR-10

### ISSUE THREAD

**Issue by 1200Caixia** [luancarvalhomartins/PyAutoFEP#70]
Ddg_vs_time does not converge in the FEP calculations of FXR_12-FXR-10. What's the reason for this problem and what can I do for it?
Protein
![image](https://user-images.githubusercontent.com/115772938/212546816-55f63f28-98ad-41f3-9ebb-083e308e9252.png)
Water
![image](https://user-images.githubusercontent.com/115772938/212546795-925cc5c3-7a73-4e45-95fa-2aec4f47ce09.png)

**Comment by luancarvalhomartins** [comment]
The reason is the intrinsic complexity of a FEP calculation. You are perturbing 12 heavy atoms using 12 lambda windows for a short simulation time. Also, convergence problems for the FXR system was observed by my group and others.

As a countermeasure, you can try simulating for a longer time, but note that it has been reported that longer simulations times (up to 20 ns) did not converge and did not improve the precision for FXR ligands ([J Comp-Aided Mol Design v. 32, pp. 265–272 (2018)](https://link.springer.com/article/10.1007/s10822-017-0064-z)).

**Comment by 1200Caixia** [comment]
Thank you for your detailed reply. I will try a longer simulation times.

**Comment by luancarvalhomartins** [comment]
Feel free to reopen should you need furhter help.
