### ISSUE TITLE
Is it possible to manually assign atom mapping when the automatic MCS(3D) searching is not satisfying?

### ISSUE THREAD

**Issue by Dead-fisher** [luancarvalhomartins/PyAutoFEP#83]
Hello,

In my case, `PyAutoFEP` asks me to use `3d` instead of `graph` because it believes there is a chiral center and the `graph` mode fails. 

But the result from the MCS(3D) searching  is like: 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43460571/234163594-254a19f6-34c3-4175-bf44-11f17202d39c.png">

which is not satisfying. Actually, my ligands just have very minor changes.

Since the MCS searching is not very smart here, is it possible to make the MCS assignment manual and avoid the conformation generation and searching? I'd like to jump to the procedure where `PyAutoFEP` generate the dual top directly from my mapping.

Thanks in advance!

**Comment by luancarvalhomartins** [comment]
Thank you for your message and sorry `PyAutoFEP` did not work as intended for you. Sorry for the tardiness, I have been super busy these last weeks.

Sure thing, you can use `mcs_custom_mcs` and `mcs_custom_atommap` to pass a custom MCS or the atom map itself to PyAutoFEP. Both support a dictionary structure to select MCS or atom maps between pair or a str to set MCS for every pair.

PS: would you mind sharing your input molecules with me? I would like to debug the 3D MCS code to make sure the underlying problem is solved.

**Comment by luancarvalhomartins** [comment]
Hope using `mcs_custom_mcs` solved the issue. In case you need more help (or is ready to share the molecules), feel free to reopen or fill another issue.
